<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/09/23 17:59:45
sfConfig::add(array(
  'app_orangehrmBeaconPlugin_version' => '1.0',
  'app_orangehrmCoreOAuthPlugin_version' => '1.0',
  'app_orangehrmCoreWebServicePlugin_version' => '1.0',
  'app_orangehrmCorporateDirectoryPlugin_version' => '1.0',
  'app_orangehrmDashboardPlugin_version' => '1.0',
  'app_orangehrm_core_leave_plugin_default_work_shift_length_hours' => 8,
  'app_orangehrmMaintenancePlugin_version' => '1.0',
  'app_orangehrmMarketPlacePlugin_version' => '1.0',
  'app_orangehrmOpenidAuthenticationPlugin_version' => '1.0',
  'app_orangehrmPerformanceTrackerPlugin_version' => '0.2',
  'app_items_per_page' => 50,
  'app_sort_asc_class' => 'ASC',
  'app_sort_desc_class' => 'DESC',
  'app_sort_default_class' => 'null',
));
