<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/09/24 06:36:16
$this->security = array (
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Admin',
        1 => 'Supervisor',
        2 => 'Manager',
      ),
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 'Admin',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
