<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/09/23 18:00:17
sfConfig::add(array(
  'mod_securityauthentication_enabled' => true,
  'mod_securityauthentication_view_class' => 'sfPHP',
));
